module.exports = {
    // 数字类型
    number:"number",
    // 字符串
    characterString: "characterString",
    // 变量名字
    variableName: "variableName",
    // 单行注解
    singleLineComment: "singleLineComments",
    // 多行注解
    multilineComment: "multilineComment",
    // 正则表达式
    regular:"regular",
    // 运算符
    operator: {
        // ++
        addOne: "addOne",
        // +
        add: "add",
        // --
        reduceOne: "reduceOne",
        // -
        reduce: "reduce",
        // *
        ride: "ride",
        // **
        involution: "involution",
        // /
        except: "except",
        // %
        remainder: "remainder",
        // =
        equal: "equal",
        // +=
        addEqual: "addEqual",
        // -=
        reduceEqual: "reduceEqual",
        // /=
        exceptEqual: "exceptEqual",
        // *=
        rideEqual: "rideEqual",
        // %=
        remainderEqual: "remainderEqual",
        // ==
        equalEqual: "equalEqual",
        // ===
        identity: "identity",
        // !=
        notEqual: "notEqual",
        // !==
        notIdentity: "notIdentity",
        // >
        greater: "greater",
        // >=
        greaterEqual: "greaterEqual",
        // <
        less: "less",
        // <=
        lessEqual: "lessEqual",
        // ? 或 :
        ternaryOperator: "ternaryOperator",
        // .
        spot: "spot",
        // !
        logicInverse: "logicInverse",
        // &
        and: "and",
        // |
        or: "or",
        // ~
        inverse: "inverse",
        // &&
        logicAnd: "logicAnd",
        // ||
        logicOr: "logicOr",
        // ^
        xor: "xor",
        // <<
        leftShift: "leftShift",
        // >>>
        rightShift: "rightShift",
        // >>
        signedRightShift: "signedRightShift",
        // ,
        comma: "comma"
    },
    // ;
    semicolon: "semicolon",
    // =>
    arrowFunction: "arrowFunction",
    // 括号
    brackets: {
        braces: {
            // {
            leftBraces: "leftBraces",
            // }
            rightBraces: "rightBraces"
        },
        middlebrackets: {
            // [
            leftMiddlebrackets: "leftMiddlebrackets",
            // ]
            rightMiddlebrackets: "rightMiddlebrackets"
        },
        parentheses: {
            // (
            leftParentheses: "leftParentheses",
            // )
            rightParentheses: "rightParentheses"
        }

    },
    jsKey: {
        abstract: "abstract",
        arguments: "arguments",
        boolean: "boolean",
        break: "break",
        byte: "byte",
        case: "case",
        catch: "catch",
        char: "char",
        class: "class",
        const: "const",
        continue: "continue",
        debugger: "debugger",
        default: "default",
        delete: "delete",
        do: "do",
        double: "double",
        else: "else",
        enum: "enum",
        eval: "eval",
        export: "export",
        extends: "extends",
        false: "false",
        final: "final",
        finally: "finally",
        float: "float",
        for: "for",
        function: "function",
        goto: "goto",
        if: "if",
        implements: "implements",
        import: "import",
        in: "in",
        instanceof: "instanceof",
        int: "int",
        interface: "interface",
        let: "let",
        long: "long",
        native: "native",
        new: "new",
        null: "null",
        package: "package",
        private: "private",
        protected: "protected",
        public: "public",
        return: "return",
        short: "short",
        static: "static",
        super: "super",
        switch: "switch",
        synchronized: "synchronized",
        this: "this",
        throw: "throw",
        throws: "throws",
        transient: "transient",
        true: "true",
        try: "try",
        typeof: "typeof",
        var: "var",
        void: "void",
        volatile: "volatile",
        while: "while",
        with: "with",
        yield: "yield"
    }
}